modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="autoeat"
version="${mod_version}"
displayName="AutoEat"
authors="Kirito"
description='''
Automatically eats food when you're hungry.
Configurable with GUI and multiple options.
'''

[[dependencies.autoeat]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.autoeat]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
